# Generated by Django 4.1.3 on 2022-12-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
